pipeline {
    agent any


    environment {
    SVC_ACCOUNT_KEY = credentials('terraform-auth')
  }
     
    stages {
        stage ('checkout'){
            steps {
                git branch: 'main', url: 'https://github.com/ishaqmdgcp/gcp-devops.git'
            }
        }
      

		stage('Set Terraform path') {
            steps {
                script {
                    def tfHome = tool name: 'Terraform'
                    env.PATH = "${tfHome}:${env.PATH}"
                }
                sh 'echo $SVC_ACCOUNT_KEY | base64 -d > ./gke-node/terraform.json'
		sh 'pwd'
                sh 'terraform --version'               
               
            }
        }
        
         stage('Provision infrastructure') {
		 steps {            
			 dir ('gke-node')
			 {
                sh 'terraform init'
                sh 'terraform plan'
                sh 'terraform apply -auto-approve'
                             
             
			 } 
        }
        }
        
      
      
    }
}
